services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KonradMichalik\Typo3LetterAvatar\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    KonradMichalik\Typo3LetterAvatar\Command\ClearAvatarsCommand:
        tags:
            - name: console.command
              command: 'avatar:clear'
              description: 'Clear all generated letter avatars.'
