type: php
docroot: .Build
additional_hostnames:
  - 11.typo3-letter-avatar
  - 12.typo3-letter-avatar
  - 13.typo3-letter-avatar
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.typo3-setup/templates/* /var/www/html/.Build/
